### PR TITLE
Taytaymarketplace v1

### PR DESCRIPTION
**Pull request by Enzuei**
Hello luds

### CODE REVIEW

**Comment by DEUX021** [comment]
taenamo

**Comment by Gelolcndli** [comment]
tite

**Comment by mariageenx** [comment]
Sarap😋

**Comment by Jurukii** [comment]
tangina mo sir

**Comment by Oniicat** [comment]
nabago yung table ng users tas eto yung file if gusto nyo i download yung table 
https://drive.google.com/drive/folders/1384N3AHdMbAw410iOKOd6gKfWAFyrz-B?usp=sharing
Tables:
users
archive_users

**Comment by Oniicat** [comment]
wala pala username field dun sa sign in page idol kaya walang ma insert na username ng user haha

**Pull request merged**
